config/routes.rb
Rails.application.routes.draw do

resources :order_checkouts

resources :main_categories do
  resources :main_category_pics
end
  

resources :main_categories do
  resources :items do 
    resources :item_pics
  end 
end

  

  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]  
 

  devise_for :users
   resources :users#, only: [:update]

  
  get 'about' => 'welcome#about'
  
  root to: 'main_categories#index'

get "checkout", to: "items#checkout"

get "purchases", to: "order_checkouts#purchases"
get "thank_you", to: "order_checkouts#thank_you"
get "seeds", to: "order_items#seeds"
post "paypal", to: "order_checkouts#pal_purchase"
post "pal_return", to: "order_checkouts#pal_return"

end

app/models/checkout_paid_item.rb
class CheckoutPaidItem < ActiveRecord::Base
  belongs_to :order_checkout
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :main_category
  has_many :item_pics
  has_many :order_items, dependent: :destroy
  default_scope { where(active: true) }
end

app/models/item_pic.rb
class ItemPic < ActiveRecord::Base
  belongs_to :item, dependent: :destroy
  mount_uploader :pic_url, PicUploader
 # serialize :description
  
  #rescue ActiveMerchant::ActiveMerchantError => e
  #self.description        = {}
  
end
#ItemPic.where(name:"template").last.description['Build']

app/models/main_category.rb
class MainCategory < ActiveRecord::Base
  has_many :main_category_pics, dependent: :destroy

  has_many :items, dependent: :destroy

end

app/models/main_category_pic.rb
class MainCategoryPic < ActiveRecord::Base
  belongs_to :main_category
  mount_uploader :pic_url, PicUploader
    serialize :description
  
  #rescue ActiveMerchant::ActiveMerchantError => e
  #self.description        = {}
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items, dependent: :destroy
  has_many :order_checkouts
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_checkout.rb
class OrderCheckout < ActiveRecord::Base
  belongs_to :order
  has_many :order_checkout_transactions, dependent: :destroy
  has_many :checkout_paid_items, dependent: :destroy
  attr_accessor :card_number, :card_verification
 # validate :validate_card, :on => :create
  
 
  
  def purchase(current_order, params)
    response = GATEWAY.purchase(
                                price_in_cents(current_order),
                                credit_card(params),
                                purchase_options(params)
                              )
    
    
    order_checkout_transactions.create!(:action => "purchase", :amount => price_in_cents(current_order), :response => response)
   # cart.update_attribute(:purchased_at, Time.now)  ## this needs to work but dont have a purchased_at attribute in any model
      if response.success?
    response.success?
      end
  end
  
  def price_in_cents(current_order)
    (current_order.subtotal*100 + 400).round 
  end

  private
  
  def purchase_options(params)
    {
      :ip => ip_address,
      :billing_address => {
        :name     => params[:order_checkout][:bill_name],
        :address1 => params[:order_checkout][:bill_adress],
        :city     => params[:order_checkout][:bill_city],
        :state    => params[:order_checkout][:bill_state],
        :country  => "US",
        :zip      => params[:order_checkout][:bill_zip]
      }
    }
  end
  
#  def validate_card(params)
 #   if !$params[:pal_button]
 #     unless credit_card.valid?
 #       credit_card.errors.full_messages.each do |message|
 #         errors.add_to_base message
#        end
 #     end
  #  end
 # end
  
  def credit_card(params)
        logger.debug puts "
                      debbuger
                      \n #{  }
                    
                      " 
               # exit
     if Rails.env.production?
   
          @credit_card ||= ActiveMerchant::Billing::CreditCard.new(

                first_name: params[:order_checkout][:first_name],
                last_name:params[:order_checkout][:last_name],
                number: params[:order_checkout][:card_number],
                month: params[:order_checkout]["card_expires_on(2i)"],
                year:params[:order_checkout]["card_expires_on(1i)"],
                verification_value: params[:order_checkout][:card_verification]   )
       else
           @credit_card ||= ActiveMerchant::Billing::CreditCard.new(

                first_name: params[:order_checkout][:first_name],
                last_name:params[:order_checkout][:last_name],
                number: params[:order_checkout][:card_number] == '' ? ENV['PAYPAL_CARD_NUMBER'] : params[:order_checkout][:card_number],
                month: params[:order_checkout]["card_expires_on(2i)"],
                year:'2020',
                verification_value: '345'   )
     end
       
  end
  
  
  
  
  
  
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :item_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      item.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def item_present
    if item.nil?
      errors.add(:item, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
          #:validatable, 
          :confirmable
 
  
   def admin?
   role == 'admin'
 end
 
 def moderator?
   role == 'moderator'
 end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  respond_to :html, :js
  def index
    @items = Item.all
    @order_item = current_order.order_items.new
  end

  def show
  end

  def new
  end
  
  def create
 
    @item = MainCategory.find(params[:main_category_id]).items.create(params.require(:item).permit(:title, :body, :name, :price))
    @item_id = @item.id
    redirect_to main_category_item_path(@item.main_category_id,@item.id)
  end

  def edit
  end
  
  def update
    
    Item.find(params[:id]).update_attributes(params.require(:item).permit(:title, :body, :name, :price) )
    redirect_to main_category_item_path(Item.find(params[:id]).main_category_id, Item.find(params[:id]).id )
  end

  def destroy
    if Item.find(params[:id]).destroy
    flash[:notice] = 'An Item was destoryed'
    end
    redirect_to root_path
  end  
  
  def checkout
    render  "items/checkout"
  end
  
  
  
end

app/controllers/main_categories_controller.rb
class MainCategoriesController < ApplicationController

  def index

  end

  def show
   
  end
  
  def create
    MainCategory.create(params.require(:main_category).permit(:title,:body,:template ) )
   # MainCategory.create(title: "test" ,body: params.inspect )
    redirect_to main_categories_path
  end

  def new
    
  end
  

  def edit
    
  end
  
  def update
    MainCategory.find(params[:id]).update_attributes(params.require(:main_category).permit(:title, :body) )
    redirect_to main_category_path(params[:id])
  end
  
  def destroy
    if MainCategory.find(params[:id]).destroy
    flash[:notice] = 'A Category was destoryed'
    end
    redirect_to root_path
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/item_pics_helper.rb
module ItemPicsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/main_categories_helper.rb
module MainCategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/main_categories/edit.html.erb
<%if $admin%>
<% @MCategory = MainCategory.find(params[:id])%>
<%= form_for @MCategory, :url => {:controller => 'main_categories', :action => 'update',  :method => 'post'} do |f| %>
<%= f.label :title%>
<%= f.text_field :title, class: 'form-control', placeholder: '' %>
<%= f.label :body %>
<%= f.text_area :body, rows: 4, class: 'form-control', placeholder: "Enter post body" %>
<%= f.submit "Save", class: 'btn btn-success' %>

<%end%>
<br>
<p>Click on Picture to Edit Picture</p>
<%if @MCategory.main_category_pics.first%>
      <%@MCategory.main_category_pics.each do |pic|%>
        <%= link_to edit_main_category_main_category_pic_path(@MCategory.id, pic.id) do%>
       <img src="<%= pic.pic_url_url%>" style='height:100px; width:100px;'>
      <%end%>
  <%end%>
<%end%>




<br><br><button><%= link_to 'Add New Pic to Category', new_main_category_main_category_pic_path(params[:id])%></button><br><br>
<%= link_to "Delete Category", [MainCategory.find(params[:id])], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this Category?' } %>
<%end%>

app/views/main_categories/index.html.erb
<%if $admin %>

<div class='col-12 seebox removempb '>

  
      <h1 style='text-align:center;'>Categories</h1>
  
  
</div>



<!-- aside div -->
<div class="col-1 vhcenterp  seebox removempb" style="height:2px;">
 </div>

<div class="col-10 seebox removempb"  >
  
  <% MainCategory.all.each do |category|%>
        <%if !category.template%>

               <h3><%= link_to category.title, main_category_items_path(category.id)%></h3>
               <p>
               <%if category.main_category_pics.first %>
                 <% pic = category.main_category_pics.first.pic_url.url %>
                 <% pic_escape = category.main_category_pics.first.urlseed %>
                  <img src="<%= (pic == nil) | (pic == "") ? pic_escape : pic %>" style='height:100px; width:100px;'>
               <%end%>
                <%= category.body%></p>
               <br><button><%= link_to "Edit This Category", edit_main_category_path(category.id) %></button>
                <hr>
              
            <%end%> 
    <%end%> 


<br><br>





      <h1>Templates</h1>

      <br>
      <% MainCategory.all.each do |category|%>
            <%if category.template%>
               <h3><%= link_to category.title, main_category_items_path(category.id)%></h3>
               <p><%= category.body%></p>
               <%if category.main_category_pics.first%>
                 <%pic = category.main_category_pics.first.pic_url.url%>
                 <%pic_escape = category.main_category_pics.first.urlseed%>
                  <img src="<%= (pic == nil) | (pic == "") ? pic_escape : pic%>" style='height:100px; width:100px;'>
               <%end%>
              <br><button><%= link_to "Edit This Category", edit_main_category_path(category.id) %></button>
          <%end%>
      <%end%>
      <br>
      <br>
      <button><%= link_to 'Make New Category', new_main_category_path%></button>
      <br><br><br><br>
<script src="assets/js/main_categories/index.js"></script>
</div>
<%end%><%# ln 1  if 1==0 on %>


<!-- ======================================test page 1==================================================================================================== -->
<%if !$admin %>
 <!-- End Top Bar -->


    <div class="col-12 orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
      <ul class="orbit-container">
        <button class="orbit-previous" aria-label="previous"><span class="show-for-sr">Previous Slide</span>&#9664;</button>
        <button class="orbit-next" aria-label="next"><span class="show-for-sr">Next Slide</span>&#9654;</button>
        <li class="orbit-slide is-active">
          <img class='orbit-image' src="https://placehold.it/2000x750">
        </li>
        <li class="orbit-slide">
          <img class='orbit-image' src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRC4Iwiwxr-myVqwN_s-u7gRUa_WA_sjWPNCv3fveujkk3_McEi">
        </li>
        <li class="orbit-slide">
          <img class='orbit-image' src="https://placehold.it/2000x750">
        </li>
        <li class="orbit-slide">
          <img class='orbit-image' src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRC4Iwiwxr-myVqwN_s-u7gRUa_WA_sjWPNCv3fveujkk3_McEi">
        </li>
      </ul>
    </div>


    <div class="row column text-center">
      <h2>Our Newest Products</h2>
      <hr>
    </div>

    <div class="row small-up-2 large-up-4">
      
 
      
   <% Item.all.each do |item|%>
       


      <div class="column">
        <%= link_to main_category_item_path(item.main_category_id, item.id) do%>
        <div class="thumbnail vhcenterp" style="width:300px; height:400px; background-color:lightgrey; " >
          <%if item.item_pics.any?%>
          <%pic = item.item_pics.first.pic_url.url%>
          <%picseed = item.item_pics.first.urlseed%>
          <%end%>
         <img class="thumbnail vhcenters" src="<%= item.item_pics.first ? (pic == nil ? picseed : pic) : "https://placehold.it/300x400" %>" style="hieght:400px;">
        </div>
        <%end%>
        <h5><%= item.name %></h5>
        <p><%= number_to_currency(item.price)%></p>
        <%= form_for current_order.order_items.new, remote: true do |f| %>
        <%= f.hidden_field :quantity, value: 1, class: "form-control", min: 1 %>
        <%= f.hidden_field :item_id, value: item.id %>
        <%= f.submit "Add to Cart", class: "button expanded" %>
        <% end %>
        
      </div> 

                <% if $admin%>
                    <br><button><%= link_to "Edit This Category", edit_main_category_path(category.id) %></button>
                <%end%>

       
<%end%> 
   
    </div>

    <hr>

    <div class="row column">
      <div class="callout primary">
        <h3>Our Departments</h3>
      </div>
    </div>

    <hr>


 <div class="row small-up-2 medium-up-3 large-up-4">
   <% MainCategory.all.each do |category|%>
   <%if !category.template%>
            <div class="column">
              <%= link_to main_category_path(category.id) do%>
              <%pic = category.main_category_pics.first.pic_url.url%>
              <%pic_escape = category.main_category_pics.first.urlseed%>
              <img class="thumbnail" src="<%= category.main_category_pics.any? ? ((pic == nil) | (pic == "") ? pic_escape : pic) : "https://placehold.it/550x550"%>">
              <%end%>
              <h5><%= category.title%></h5>
            </div>
   <%end%>
   <%end%>
      
          </div>



    <div class="row column">
      <div class="callout primary">
        <h3>Really big special this week on items.</h3>
      </div>
    </div>

    <hr>

    <div class="row column text-center">
      <h2>Some Other Neat Products</h2>
      <hr>
    </div>

    <div class="row small-up-2 medium-up-3 large-up-6">
      <div class="column">
        <img class="thumbnail" src="https://placehold.it/300x400">
        <h5>Nulla At Nulla Justo, Eget</h5>
        <p>$400</p>
        <a href="#" class="button small expanded hollow">Buy</a>
      </div>
      <div class="column">
        <img class="thumbnail" src="https://placehold.it/300x400">
        <h5>Nulla At Nulla Justo, Eget</h5>
        <p>$400</p>
        <a href="#" class="button small expanded hollow">Buy</a>
      </div>
      <div class="column">
        <img class="thumbnail" src="https://placehold.it/300x400">
        <h5>Nulla At Nulla Justo, Eget</h5>
        <p>$400</p>
        <a href="#" class="button small expanded hollow">Buy</a>
      </div>
      <div class="column">
        <img class="thumbnail" src="https://placehold.it/300x400">
        <h5>Nulla At Nulla Justo, Eget</h5>
        <p>$400</p>
        <a href="#" class="button small expanded hollow">Buy</a>
      </div>
      <div class="column">
        <img class="thumbnail" src="https://placehold.it/300x400">
        <h5>Nulla At Nulla Justo, Eget</h5>
        <p>$400</p>
        <a href="#" class="button small expanded hollow">Buy</a>
      </div>
      <div class="column">
        <img class="thumbnail" src="https://placehold.it/300x400">
        <h5>Nulla At Nulla Justo, Eget</h5>
        <p>$400</p>
        <a href="#" class="button small expanded hollow">Buy</a>
      </div>
    </div>

    <hr>
   

    <div class="callout large secondary">
      <div class="row">
        <div class="large-4 columns">
          <h5>Vivamus Hendrerit Arcu Sed Erat Molestie</h5>
          <p>Curabitur vulputate, ligula lacinia scelerisque tempor, lacus lacus ornare ante, ac egestas est urna sit amet arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed molestie augue sit.</p>
        </div>
        <div class="large-3 large-offset-2 columns">
          <ul class="menu vertical">
            <li><a href="#">One</a></li>
            <li><a href="#">Two</a></li>
            <li><a href="#">Three</a></li>
            <li><a href="#">Four</a></li>
          </ul>
        </div>
        <div class="large-3 columns">
          <ul class="menu vertical">
            <li><a href="#">One</a></li>
            <li><a href="#">Two</a></li>
            <li><a href="#">Three</a></li>
            <li><a href="#">Four</a></li>
          </ul>
        </div>
      </div>
    </div>

   
 
    

<%end%>

app/views/main_categories/new.html.erb
<%if $admin%>
<h1>Create New Categroy</h1>

<br>
<%= form_for MainCategory.new, :url => {:controller => 'main_categories', :action => 'create',  :method => 'post'} do |f|%>
<br><%= f.label :title%>
<br><%= f.text_field :title, class: 'form-control', placeholder: "Enter A Title" %>
<%= f.label :body %>
<%= f.text_area :body, rows: 5, class: 'form-control', placeholder: "Enter description" %>
<%= f.label "Template?" %>
<%= f.check_box :template, {}, true, false %> <br />

<%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>

<%end%>

app/views/main_categories/show.html.erb
<%if $admin%>
<% @MCategoryItem = MainCategory.find(params[:id]).items %>
<% @MCategoryItem.each do |this|%>
<h3><%= link_to this.title, edit_main_category_path(params[:id])%></h3>
<p><%= this.body%></p>
  <% this.item_pics.each do |pic|%>
      <%= link_to edit_main_category_main_category_pic_path(params[:id], pic.id) do %>
        <img src="<%= pic.pic_url.url%>" style='height:100px; width:100px; margin-right:30px;'>
    <%end%>
  <%end%>
<%end%>

<br><br><button><%= link_to "Edit Category", edit_main_category_path(params[:id]) %></button>
<%end%>
<!-- ======================================================================================================= -->

<%if !$admin%>
<%@items = MainCategory.find(params[:id]).items%>
<%if @items.any?%>
<%@items.each do |item|%>
<% if item.item_pics.any?%>
<%pic = item.item_pics.first.pic_url.url%>
<%pic_seed = item.item_pics.first.urlseed%>
<%end%>
    <div class="row">
      <div class="medium-6 columns">
        <img class="thumbnail" src="<%= item.item_pics.any? ? (pic == nil ? pic_seed : pic) : "https://placehold.it/650x350"%>">
        <div class="row small-up-4">
          <div class="column">
            <img class="thumbnail" src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRC4Iwiwxr-myVqwN_s-u7gRUa_WA_sjWPNCv3fveujkk3_McEi">
          </div>
          <div class="column">
            <img class="thumbnail" src="https://placehold.it/250x200">
          </div>
          <div class="column">
            <img class="thumbnail" src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRC4Iwiwxr-myVqwN_s-u7gRUa_WA_sjWPNCv3fveujkk3_McEi">
          </div>
          <div class="column">
            <img class="thumbnail" src="https://placehold.it/250x200">
          </div>
        </div>
      </div>
      <div class="medium-6 large-5 columns">
        <h3><%= item.title %></h3>
        <p>Nunc eu ullamcorper orci. Quisque eget odio ac lectus vestibulum faucibus eget in metus. In pellentesque faucibus vestibulum. Nulla at nulla justo, eget luctus tortor. Nulla facilisi. Duis aliquet egestas purus in.</p>



        

      <%= form_for current_order.order_items.new, remote: true do |f| %>
      <div class="row">
          <div class="small-3 columns">
          <label for="middle-label" class="middle">Quantity</label>
             <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          </div>
          <div class="small-9 columns"> 
          </div>
      </div>

      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency item.price %></span></h4>
        <div class="input-group">
          <div class="input-group-btn">
            <%= f.hidden_field :item_id, value: item.id %>
            <%= f.submit "Add to Cart", class: "button large expanded" %>
          </div>
        </div>
      <% end %>

        <div class="small secondary expanded button-group">
            <a class="button">Facebook</a>
            <a class="button">Twitter</a>
            <a class="button">Yo</a>
          </div>
        </div>
      
      <div class="col-12  vhcenterp" style="height:70px;margin-top:20px;">
           <div class="col-10 button col-p-10 vhcenters" style="height:80%;  background-color:lightgrey;"><h3 class="vhcenters">More info and Reviews!!</h3>  </div>
        
        </div>
      
      
    </div>
<div class="col-12" style="height:100px;"></div>
<hr>

<%end%>
<%else%>

<div class="col-12 vhcenterp seebox"  style="height:400px;">
    <div class="col-10 vhcenters seebox"><h1 class="center">We are Sorry :( But this category has no items yet.</h1>
      </div>
</div>

<%end%>
<%end%>