config/routes.rb
Rails.application.routes.draw do

resources :order_checkouts

resources :main_categories do
  resources :main_category_pics
end
  

resources :main_categories do
  resources :items do 
    resources :item_pics
  end 
end

  

  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]  
 

  devise_for :users
   resources :users#, only: [:update]

  
  get 'about' => 'welcome#about'
  
  root to: 'main_categories#index'

get "checkout", to: "items#checkout"

get "purchases", to: "order_checkouts#purchases"
get "thank_you", to: "order_checkouts#thank_you"
get "seeds", to: "order_items#seeds"
post "paypal", to: "order_checkouts#pal_purchase"
post "pal_return", to: "order_checkouts#pal_return"

end

app/models/checkout_paid_item.rb
class CheckoutPaidItem < ActiveRecord::Base
  belongs_to :order_checkout
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :main_category
  has_many :item_pics
  has_many :order_items, dependent: :destroy
  default_scope { where(active: true) }
end

app/models/item_pic.rb
class ItemPic < ActiveRecord::Base
  belongs_to :item, dependent: :destroy
  mount_uploader :pic_url, PicUploader
 # serialize :description
  
  #rescue ActiveMerchant::ActiveMerchantError => e
  #self.description        = {}
  
end
#ItemPic.where(name:"template").last.description['Build']

app/models/main_category.rb
class MainCategory < ActiveRecord::Base
  has_many :main_category_pics, dependent: :destroy

  has_many :items, dependent: :destroy

end

app/models/main_category_pic.rb
class MainCategoryPic < ActiveRecord::Base
  belongs_to :main_category
  mount_uploader :pic_url, PicUploader
    serialize :description
  
  #rescue ActiveMerchant::ActiveMerchantError => e
  #self.description        = {}
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items, dependent: :destroy
  has_many :order_checkouts
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_checkout.rb
class OrderCheckout < ActiveRecord::Base
  belongs_to :order
  has_many :order_checkout_transactions, dependent: :destroy
  has_many :checkout_paid_items, dependent: :destroy
  attr_accessor :card_number, :card_verification
 # validate :validate_card, :on => :create
  
 
  
  def purchase(current_order, params)
    response = GATEWAY.purchase(
                                price_in_cents(current_order),
                                credit_card(params),
                                purchase_options(params)
                              )
    
    
    order_checkout_transactions.create!(:action => "purchase", :amount => price_in_cents(current_order), :response => response)
   # cart.update_attribute(:purchased_at, Time.now)  ## this needs to work but dont have a purchased_at attribute in any model
      if response.success?
    response.success?
      end
  end
  
  def price_in_cents(current_order)
    (current_order.subtotal*100 + 400).round 
  end

  private
  
  def purchase_options(params)
    {
      :ip => ip_address,
      :billing_address => {
        :name     => params[:order_checkout][:bill_name],
        :address1 => params[:order_checkout][:bill_adress],
        :city     => params[:order_checkout][:bill_city],
        :state    => params[:order_checkout][:bill_state],
        :country  => "US",
        :zip      => params[:order_checkout][:bill_zip]
      }
    }
  end
  
#  def validate_card(params)
 #   if !$params[:pal_button]
 #     unless credit_card.valid?
 #       credit_card.errors.full_messages.each do |message|
 #         errors.add_to_base message
#        end
 #     end
  #  end
 # end
  
  def credit_card(params)
        logger.debug puts "
                      debbuger
                      \n #{  }
                    
                      " 
               # exit
     if Rails.env.production?
   
          @credit_card ||= ActiveMerchant::Billing::CreditCard.new(

                first_name: params[:order_checkout][:first_name],
                last_name:params[:order_checkout][:last_name],
                number: params[:order_checkout][:card_number],
                month: params[:order_checkout]["card_expires_on(2i)"],
                year:params[:order_checkout]["card_expires_on(1i)"],
                verification_value: params[:order_checkout][:card_verification]   )
       else
           @credit_card ||= ActiveMerchant::Billing::CreditCard.new(

                first_name: params[:order_checkout][:first_name],
                last_name:params[:order_checkout][:last_name],
                number: params[:order_checkout][:card_number] == '' ? ENV['PAYPAL_CARD_NUMBER'] : params[:order_checkout][:card_number],
                month: params[:order_checkout]["card_expires_on(2i)"],
                year:'2020',
                verification_value: '345'   )
     end
       
  end
  
  
  
  
  
  
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :item_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      item.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def item_present
    if item.nil?
      errors.add(:item, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
          #:validatable, 
          :confirmable
 
  
   def admin?
   role == 'admin'
 end
 
 def moderator?
   role == 'moderator'
 end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  respond_to :html, :js
  def index
    @items = Item.all
    @order_item = current_order.order_items.new
  end

  def show
  end

  def new
  end
  
  def create
 
    @item = MainCategory.find(params[:main_category_id]).items.create(params.require(:item).permit(:title, :body, :name, :price))
    @item_id = @item.id
    redirect_to main_category_item_path(@item.main_category_id,@item.id)
  end

  def edit
  end
  
  def update
    
    Item.find(params[:id]).update_attributes(params.require(:item).permit(:title, :body, :name, :price) )
    redirect_to main_category_item_path(Item.find(params[:id]).main_category_id, Item.find(params[:id]).id )
  end

  def destroy
    if Item.find(params[:id]).destroy
    flash[:notice] = 'An Item was destoryed'
    end
    redirect_to root_path
  end  
  
  def checkout
    render  "items/checkout"
  end
  
  
  
end

app/controllers/users_controller.rb
 class UsersController < ApplicationController
   before_action :authenticate_user!
 
   def update
     if current_user.update_attributes(user_params)
       flash[:notice] = "User information updated"
       redirect_to edit_user_registration_path
     else
       flash[:error] = "Invalid user information"
       redirect_to edit_user_registration_path
     end
   end
 
   private
 
   def user_params
     params.require(:user).permit(:name)
   end
 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/item_pics_helper.rb
module ItemPicsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_item_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><small><%= link_to item.title, main_category_item_path(item.main_category_id, item.id)  %></small></h4><br>
       <% if item.item_pics.any?%>
      <%pic = item.item_pics.first.pic_url.url%>
      <%pic_seed = item.item_pics.first.urlseed %>
      <img src="<%= pic == nil ? pic_seed : pic %>" style='height:100px; width:100px;'>
      <%end%>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency item.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :item_id, value: item.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
    <%if $admin%>
      <br><button><%= link_to "Add Pics", new_main_category_item_item_pic_path(item.main_category_id, item.id)%></button>
      <br><button><%= link_to "Edit Item", edit_main_category_item_path(params[:main_category_id], item.id) %></button>
    <%end%>
  </div>
</div>

app/views/items/checkout.html.erb
<% form_for "#" do |f| %>
 
  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :card_type %><br />
    <%= f.select :card_type, [["Visa", "visa"], ["MasterCard", "master"], ["Discover", "discover"], ["American Express", "american_express"]] %>
  </p>
  <p>
    <%= f.label :card_number %><br />
    <%= f.text_field :card_number %>
  </p>
  <p>
    <%= f.label :card_verification, "Card Verification Value (CVV)" %><br />
    <%= f.text_field :card_verification %>
  </p>
  <p>
    <%= f.label :card_expires_on %><br />
    <%= f.date_select :card_expires_on, :discard_day => true, :start_year => Date.today.year, :end_year => (Date.today.year+10), :add_month_numbers => true %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>
<p>hello<p>

app/views/items/edit.html.erb
<%if $admin%>
<% @item = Item.find(params[:id])%>
<%= form_for @item, :url => {:controller => 'items', :action => 'update',  :method => 'post'} do |f| %>
<%= f.label :title%>
<%= f.text_field :title, class: 'form-control', placeholder: '' %>
<%= f.label :body %>
<%= f.text_area :body, rows: 4, class: 'form-control', placeholder: "Enter item body" %>
<br><%= f.label :price%>
<br><%= f.number_field :price, class: 'form-control', placeholder: "Enter A Title" %>
<%= f.submit "Save", class: 'btn btn-success' %>

<%end%>
<br>
<p>Click on Picture to Edit Picture</p>
<%if @item.item_pics.first%>
      <%@item.item_pics.each do |pic|%>
        <%= link_to edit_main_category_item_item_pic_path(@item.main_category_id, @item.id, pic.id) do%>
       <img src="<%= pic.pic_url_url%>" style='height:100px; width:100px;'>
      <%end%>
  <%end%>
<%end%>




<br><br><button><%= link_to 'Add New Pic to Item', new_main_category_item_item_pic_path(@item.main_category_id, @item.id)%></button><br><br>
<%= link_to "Delete Item", [MainCategory.find(@item.main_category_id), Item.find(@item.id) ], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this Category?' } %>
<%end%>

app/views/items/index.html.erb
<% @items = MainCategory.find(params[:main_category_id]).items%>
<h3><%= link_to "Back to Categorys", root_path%><h3>
  <h3 class="text-center">Products for Sale</h3>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @items.each do |item| %>
      <%= render "item_row", item: item, order_item: @order_item %>
    <% end %>
  </div>
</div>  
  
  
  
<%if $admin%>
<br><br><button><%= link_to "Add Item", new_main_category_item_path(params[:main_category_id]) %></button><br><br><br><br>
<%end%>  
  

  

app/views/items/new.html.erb
<%if $admin%>
<h1>Create New Categroy</h1>

<br>
<%= form_for Item.new, :url => {:controller => 'items', :action => 'create',  :method => 'post'} do |f|%>
<br><%= f.label :title%>
<br><%= f.text_field :title, class: 'form-control', placeholder: "Enter A name" %>
<br><%= f.label :name%>
<br><%= f.text_field :name, class: 'form-control', placeholder: "Enter A name" %>
<br><%= f.label :price%>
<br><%= f.number_field :price, class: 'form-control', placeholder: "Enter A Title" %>
<%= f.label :body %>
<%= f.text_area :body, rows: 5, class: 'form-control', placeholder: "Enter description" %>
<%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
<%end%>

app/views/items/show.html.erb
<% @item = Item.find(params[:id])%>
<%if @item.item_pics.any?%>
<%pic = @item.item_pics.first.pic_url.url%>
<%pic_seed = @item.item_pics.first.urlseed%>
<%end%>

<%if 1==0%>
<h3><%= link_to 'Back to Category Items', main_category_items_path(@item.main_category_id) %><h3>

<h3><%= @item.title %></h3>
<p>name:<%= @item.name %></p>
<p><%= @item.body %></p>
<p>price:<%= @item.price %></p>  
<%if @item.item_pics.any?%>
<%@item.item_pics.each do |pic|%>
<img src="<%= pic.pic_url_url%>" style="height:150px; width:150px;">
  
<% end%>
<%end %>
  <br>

  

  
     <%= form_for current_order.order_items.new, remote: true do |f| %>
 
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency @item.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :item_id, value: @item.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
  <% if $admin%>
  <br><br><br><br><button><%= link_to 'ADD Pictures to Item', new_main_category_item_item_pic_path(params[:main_category_id], params[:id]) %></button>
 <br><button><%= link_to "Edit Item", edit_main_category_item_path(@item.main_category_id, @item.id) %></button>
  <%end%>
  
  <%end%>
  
<!--   ====================================test page 1======================================================= -->



    <div class="row">
      <div class="medium-6 columns">

        <img class="thumbnail" src="<%= @item.item_pics.any? ? (pic == nil ? pic_seed : pic): "https://placehold.it/650x350"%>">
        <div class="row small-up-4">
          <div class="column">
            <img class="thumbnail" src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRC4Iwiwxr-myVqwN_s-u7gRUa_WA_sjWPNCv3fveujkk3_McEi">
          </div>
          <div class="column">
            <img class="thumbnail" src="https://placehold.it/250x200">
          </div>
          <div class="column">
            <img class="thumbnail" src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRC4Iwiwxr-myVqwN_s-u7gRUa_WA_sjWPNCv3fveujkk3_McEi">
          </div>
          <div class="column">
            <img class="thumbnail" src="https://placehold.it/250x200">
          </div>
        </div>
      </div>
      <div class="medium-6 large-5 columns">
        <h3><%= @item.title %></h3>
        <p>Nunc eu ullamcorper orci. Quisque eget odio ac lectus vestibulum faucibus eget in metus. In pellentesque faucibus vestibulum. Nulla at nulla justo, eget luctus tortor. Nulla facilisi. Duis aliquet egestas purus in.</p>



        

      <%= form_for current_order.order_items.new, remote: true do |f| %>
      <div class="row">
          <div class="small-3 columns">
          <label for="middle-label" class="middle">Quantity</label>
             <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          </div>
          <div class="small-9 columns"> 
          </div>
      </div>

      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency @item.price %></span></h4>
        <div class="input-group">
          <div class="input-group-btn">
            <%= f.hidden_field :item_id, value: @item.id %>
            <%= f.submit "Add to Cart", class: "button large expanded" %>
          </div>
        </div>
      <% end %>

        
        
        
        

        <div class="small secondary expanded button-group">
            <a class="button">Facebook</a>
            <a class="button">Twitter</a>
            <a class="button">Yo</a>
          </div>
        </div>
    </div>

    <div class="column row">
      <hr>
      <ul class="tabs" data-tabs id="example-tabs">
        <li class="tabs-title is-active"><a href="#panel1" aria-selected="true">Reviews</a></li>
        <li class="tabs-title"><a href="#panel2">Similar Products</a></li>
      </ul>
      <div class="tabs-content" data-tabs-content="example-tabs">
        <div class="tabs-panel is-active" id="panel1">
          <h4>Reviews</h4>
          <div class="media-object stack-for-small">
            <div class="media-object-section">
              <img class="thumbnail" src="https://placehold.it/200x200">
            </div>
            <div class="media-object-section">
              <h5>Mike Stevenson</h5>
              <p>I'm going to improvise. Listen, there's something you should know about me... about inception. An idea is like a virus, resilient, highly contagious. The smallest seed of an idea can grow. It can grow to define or destroy you.</p>
            </div>
          </div>
          <div class="media-object stack-for-small">
            <div class="media-object-section">
              <img class="thumbnail" src="https://placehold.it/200x200">
            </div>
            <div class="media-object-section">
              <h5>Mike Stevenson</h5>
              <p>I'm going to improvise. Listen, there's something you should know about me... about inception. An idea is like a virus, resilient, highly contagious. The smallest seed of an idea can grow. It can grow to define or destroy you</p>
            </div>
          </div>
          <div class="media-object stack-for-small">
            <div class="media-object-section">
              <img class="thumbnail" src="https://placehold.it/200x200">
            </div>
            <div class="media-object-section">
              <h5>Mike Stevenson</h5>
              <p>I'm going to improvise. Listen, there's something you should know about me... about inception. An idea is like a virus, resilient, highly contagious. The smallest seed of an idea can grow. It can grow to define or destroy you</p>
            </div>
          </div>
          <label>
            My Review
            <textarea placeholder="None"></textarea>
          </label>
          <button class="button">Submit Review</button>
        </div>
        <div class="tabs-panel" id="panel2">
          <div class="row medium-up-3 large-up-5">
            <div class="column">
              <img class="thumbnail" src="https://placehold.it/350x200">
              <h5>Other Product <small>$22</small></h5>
              <p>In condimentum facilisis porta. Sed nec diam eu diam mattis viverra. Nulla fringilla, orci ac euismod semper, magna diam.</p>
              <a href="#" class="button hollow tiny expanded">Buy Now</a>
            </div>
            <div class="column">
              <img class="thumbnail" src="https://placehold.it/350x200">
              <h5>Other Product <small>$22</small></h5>
              <p>In condimentum facilisis porta. Sed nec diam eu diam mattis viverra. Nulla fringilla, orci ac euismod semper, magna diam.</p>
              <a href="#" class="button hollow tiny expanded">Buy Now</a>
            </div>
            <div class="column">
              <img class="thumbnail" src="https://placehold.it/350x200">
              <h5>Other Product <small>$22</small></h5>
              <p>In condimentum facilisis porta. Sed nec diam eu diam mattis viverra. Nulla fringilla, orci ac euismod semper, magna diam.</p>
              <a href="#" class="button hollow tiny expanded">Buy Now</a>
            </div>
            <div class="column">
              <img class="thumbnail" src="https://placehold.it/350x200">
              <h5>Other Product <small>$22</small></h5>
              <p>In condimentum facilisis porta. Sed nec diam eu diam mattis viverra. Nulla fringilla, orci ac euismod semper, magna diam.</p>
              <a href="#" class="button hollow tiny expanded">Buy Now</a>
            </div>
            <div class="column">
              <img class="thumbnail" src="https://placehold.it/350x200">
              <h5>Other Product <small>$22</small></h5>
              <p>In condimentum facilisis porta. Sed nec diam eu diam mattis viverra. Nulla fringilla, orci ac euismod semper, magna diam.</p>
              <a href="#" class="button hollow tiny expanded">Buy Now</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row column">
      <hr>
      <ul class="menu">
        <li>Yeti Store</li>
        <li><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
        <li class="float-right">Copyright 2016</li>
      </ul>
    </div>


    
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"></script>
    <script>
      $(document).foundation();
    </script>
  
  