config/routes.rb
Rails.application.routes.draw do

resources :order_checkouts

resources :main_categories do
  resources :main_category_pics
end
  

resources :main_categories do
  resources :items do 
    resources :item_pics
  end 
end

  

  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]  
 

  devise_for :users
   resources :users#, only: [:update]

  
  get 'about' => 'welcome#about'
  
  root to: 'main_categories#index'

get "checkout", to: "items#checkout"

get "purchases", to: "order_checkouts#purchases"
get "thank_you", to: "order_checkouts#thank_you"
get "seeds", to: "order_items#seeds"
post "paypal", to: "order_checkouts#pal_purchase"
post "pal_return", to: "order_checkouts#pal_return"

end

app/models/order_checkout.rb
class OrderCheckout < ActiveRecord::Base
  belongs_to :order
  has_many :order_checkout_transactions, dependent: :destroy
  has_many :checkout_paid_items, dependent: :destroy
  attr_accessor :card_number, :card_verification
 # validate :validate_card, :on => :create
  
 
  
  def purchase(current_order, params)
    response = GATEWAY.purchase(
                                price_in_cents(current_order),
                                credit_card(params),
                                purchase_options(params)
                              )
    
    
    order_checkout_transactions.create!(:action => "purchase", :amount => price_in_cents(current_order), :response => response)
   # cart.update_attribute(:purchased_at, Time.now)  ## this needs to work but dont have a purchased_at attribute in any model
      if response.success?
    response.success?
      end
  end
  
  def price_in_cents(current_order)
    (current_order.subtotal*100 + 400).round 
  end

  private
  
  def purchase_options(params)
    {
      :ip => ip_address,
      :billing_address => {
        :name     => params[:order_checkout][:bill_name],
        :address1 => params[:order_checkout][:bill_adress],
        :city     => params[:order_checkout][:bill_city],
        :state    => params[:order_checkout][:bill_state],
        :country  => "US",
        :zip      => params[:order_checkout][:bill_zip]
      }
    }
  end
  
#  def validate_card(params)
 #   if !$params[:pal_button]
 #     unless credit_card.valid?
 #       credit_card.errors.full_messages.each do |message|
 #         errors.add_to_base message
#        end
 #     end
  #  end
 # end
  
  def credit_card(params)
        logger.debug puts "
                      debbuger
                      \n #{  }
                    
                      " 
               # exit
     if Rails.env.production?
   
          @credit_card ||= ActiveMerchant::Billing::CreditCard.new(

                first_name: params[:order_checkout][:first_name],
                last_name:params[:order_checkout][:last_name],
                number: params[:order_checkout][:card_number],
                month: params[:order_checkout]["card_expires_on(2i)"],
                year:params[:order_checkout]["card_expires_on(1i)"],
                verification_value: params[:order_checkout][:card_verification]   )
       else
           @credit_card ||= ActiveMerchant::Billing::CreditCard.new(

                first_name: params[:order_checkout][:first_name],
                last_name:params[:order_checkout][:last_name],
                number: params[:order_checkout][:card_number] == '' ? ENV['PAYPAL_CARD_NUMBER'] : params[:order_checkout][:card_number],
                month: params[:order_checkout]["card_expires_on(2i)"],
                year:'2020',
                verification_value: '345'   )
     end
       
  end
  
  
  
  
  
  
end

app/controllers/order_checkouts_controller.rb
class OrderCheckoutsController < ApplicationController
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
  respond_to :html, :js
  
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
  
  def create
    
   
  #@order = current_cart.build_order(params[:order])  price_in

    li1 = "#{params[:order_checkout]['card_expires_on(1i)']}"
    li2 = "-#{params[:order_checkout]['card_expires_on(2i)']}"
    li3 = "-#{params[:order_checkout]['card_expires_on(3i)']}"
    card_exp_date = li1+li2+li3
  @order = OrderCheckout.create(Order_id: current_order.id,
                                first_name: params[:order_checkout][:first_name] == '' ? current_order.order_checkouts.last.first_name : params[:order_checkout][:first_name] ,
                                last_name: params[:order_checkout][:last_name] == '' ? current_order.order_checkouts.last.last_name : params[:order_checkout][:last_name] ,
                                email: params[:order_checkout][:email] == '' ? current_order.order_checkouts.last.email : params[:order_checkout][:email] ,
                                phone: params[:order_checkout][:phone] == '' ? current_order.order_checkouts.last.phone : params[:order_checkout][:phone] ,
                                adress: params[:order_checkout][:adress] == '' ? current_order.order_checkouts.last.adress : params[:order_checkout][:adress] ,
                                city: params[:order_checkout][:city] == '' ? current_order.order_checkouts.last.city : params[:order_checkout][:city] ,
                                state: params[:order_checkout][:state] == '' ? current_order.order_checkouts.last.state : params[:order_checkout][:state] ,
                                zip: params[:order_checkout][:zip] == '' ? current_order.order_checkouts.last.zip : params[:order_checkout][:zip] ,
                                bill_name: params[:order_checkout][:bill_name] == '' ? current_order.order_checkouts.last.bill_name : params[:order_checkout][:bill_name] ,
                                bill_adress: params[:order_checkout][:bill_adress] == '' ? current_order.order_checkouts.last.bill_adress : params[:order_checkout][:bill_adress] ,
                                bill_city: params[:order_checkout][:bill_city] == '' ? current_order.order_checkouts.last.bill_city : params[:order_checkout][:bill_city] ,
                                bill_state: params[:order_checkout][:bill_state] == '' ? current_order.order_checkouts.last.bill_state : params[:order_checkout][:bill_state] ,
                                bill_zip: params[:order_checkout][:bill_zip] == '' ? current_order.order_checkouts.last.bill_zip : params[:order_checkout][:bill_zip] ,   
                                card_type: params[:order_checkout][:card_type],
                                card_expires_on: card_exp_date,
                                instructions: params[:order_checkout][:instructions]
                                )
    
  @order.ip_address = request.remote_ip
# @order.validate_card(params)
  if @order.save
    if @order.purchase(current_order, params)
      @order.update_attributes(purchased_at: DateTime.now  )     
       current_order.order_items.each do |item|
         Item.find(item.item_id) do |itemIn|
           OrderCheckout.find(@order.id).checkout_paid_items.create(title: itemIn.title, name: itemIn.name, price:itemIn.price, body: itemIn.body)
          end
      end   
    
      current_order.order_items.destroy_all
      #render :action => "success"
      redirect_to thank_you_path
    else
     
      render :action => "failure"
    end
    else
     
      render :action => 'new'
    end
   
  end
  
  
  
  
  def pal_purchase
   # $params = params
    #$current_order = current_order 
    a = []
    b = []
    current_order.order_items.each do |item|
      a << item.id.to_s 
      b << Item.find(item.item_id).name
          end
    
    logger.debug puts "
                      debbuger
                      \n #{a.to_s}
                      \n #{b.to_s}
                      \n currnt_order-> #{current_order.inspect }
                      \n currnt_order.order_items-> \n #{current_order.order_items.inspect } 
                      \n currnt_order.subtotal-> #{current_order.subtotal }
                      
                      " 
               # exit
    
    
    if current_order.order_items.any? 
         @retun_values={
                      
                      item_id: a.to_s ,
                       item_name: b.to_s,
                       order_id: current_order.id,
                      # email: current_user.email,
                       #item_sub_category:@item.sub_category_id
                       }
            values = {
                      business: "migs432-facilitator@yahoo.com ",
                      cmd: "_cart",
                      upload: 1,
                      return: "#{request.base_url}/thank_you",#/pal_return?user_id=#{@retun_values[:order_id]}&authenticity_token=#{form_authenticity_token}&pal_button=true&method=post",
                      notify_url: "#{request.base_url}/pal_return?order_id=#{@retun_values[:order_id]}&authenticity_token=#{form_authenticity_token}&pal_button=true&method=post",
                      handling_cart: "4.00",
                      shopping_url: "#{request.base_url}/"
                      #display: "1"
                      }
      
      current_order.order_items.each_with_index do |item, index|
                        values.merge!({
                                      # :add => "#{index+1}",  
                                       :"amount_#{index+1}" => item.unit_price.to_s,
                                       :"item_name_#{index+1}"=> Item.find(item.item_id).name,
                                       :"item_number_#{index+1}"=> item.item_id,
                                       :"quantity_#{index+1}"=> item.quantity,
                                    })
                      end
         redirect_to "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
      
     else
         flash[:error] = "There was an error saving the Category. Please try again."

     end
    
    
    
  end
  
  
  def pal_return
#=begin
   
    OrderCheckout.create(instructions: params.to_s)
   
    
   # redirect_to root_path
#=end
    
#=begin
  
 #   li1 = "#{params[:order_checkout]['card_expires_on(1i)']}"
 #   li2 = "-#{params[:order_checkout]['card_expires_on(2i)']}"
 #   li3 = "-#{params[:order_checkout]['card_expires_on(3i)']}"
 #   card_exp_date = li1+li2+li3
  @order = OrderCheckout.create(Order_id: params[:order_id],
                                first_name: params[:first_name] ,
                                last_name:  params[:last_name] ,
                                email: params[:payer_email] ,
                                adress:  params[:address_street] ,
                                city: params[:address_city] ,
                                state:params[:address_state] ,
                                zip: params[:address_zip] ,
                                bill_name:params[:address_name] ,
                                bill_adress:  params[:address_street] ,
                                bill_city: params[:address_city] ,
                                bill_state:  params[:address_state] ,
                                bill_zip: params[:address_zip] ,  
                                instructions: params.to_s
                                )
    
   @Order = Order.find(params[:order_id])
    @OrderCheckout = @Order.order_checkouts.last
    
 # OrderCheckoutTransaction.create!(order_checkout_id:params[:order_id],success: true, params: params.to_s, authorization: params[:payment_status],  :amount => params[:payment_gross]).default_connection_handler
    @OrderCheckout.order_checkout_transactions.create!(success: true, params: params, authorization: params[:payment_status],  :amount => params[:payment_gross]).default_connection_handler
    #order_checkout_transactions.palreturn(params)
         @OrderCheckout.update_attributes(purchased_at: DateTime.now  )     
       @Order.order_items.each do |item|
         Item.find(item.item_id) do |itemIn|
           OrderCheckout.find(@OrderCheckout.id).checkout_paid_items.create(title: itemIn.title, name: itemIn.name, price:itemIn.price, body: itemIn.body)
          end
      end   
    
      
    @Order.order_items.destroy_all
    
#=end
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
  end
  
  
  
  def purchases
    render "purchases"
  end
  
  def destroy
  @order_checkout = OrderCheckout.find(params[:id])
  @order_checkout.update_attributes(paid_shipped_n_done: true)

  end

    def update
  @order_checkout = OrderCheckout.find(params[:id])
  @order_checkout.update_attributes(paid_shipped_n_done: true)

  end
  
  def thank_you
  
  end
  

  private
  
  def clean_params
  
    
  end
  
  
  
  
  
  
  
  
  
  
end

app/helpers/order_checkouts_helper.rb
module OrderCheckoutsHelper
end

app/views/order_checkouts/destroy.js.erb
 <% if this.destroy? %>
   $('#order_checkout-' +<%= this.id %>).hide();
 <% else %>
   $('#order_checkout-' +<%= this.id %>).prepend("<div class='alert alert-danger'><%= flash[:error] %></div>");
 <% end %>

app/views/order_checkouts/edit.html.erb
<h1>OrderCheckouts#edit</h1>
<p>Find me in app/views/order_checkouts/edit.html.erb</p>

app/views/order_checkouts/failure.html.erb
<h1>OOPS!</h1>
<p>something went wrong!</p>
<p>possibility could be wrong card number or bad expiration date or no funds or mysterious bank problem</p>
<h2>please Try agian with new card or just review card details</h2>
<button><%= link_to 'Try Again', new_order_checkout_path%></button>

app/views/order_checkouts/index.html.erb
<h1>OrderCheckouts#index</h1>
<p>Find me in app/views/order_checkouts/index.html.erb</p>

app/views/order_checkouts/new.html.erb
 
<div class="col-1"></div>

<div class="col-10" style="display:none;" id="instore-form">
  
  <div class="col-11 col-p-11" style="margin:30px;">
    
  <%= link_to paypal_path, method: :post do %> 
  <img src="<%request.base_url%>/assets/images/paypal.gif" class="center" style=" float:right; width:180px; height:60px;"><br>
    <%end%>
  <img src="<%request.base_url%>/assets/images/hand.gif" class="center" style="float:right; width:40px; height:40px;">
</div>
  
<!--   right-aside space for image-->
  <div class="col-1 col-p-1"></div>
  
 
  
  
  
  
<%= form_for OrderCheckout.new, :url => {:controller => 'order_checkouts', :action => 'create',  :method => 'post'} do |f| %>

<h3>Shipping Address</h3>
  
  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, placeholder: current_order.order_checkouts.any? ? current_order.order_checkouts.last.first_name : '' %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name , placeholder: current_order.order_checkouts.any? ? current_order.order_checkouts.last.last_name : ''  %>
  </p>

 <p>
    <%= f.label :email %><br />
    <%= f.text_field :email , placeholder: current_order.order_checkouts.any? ? current_order.order_checkouts.last.email : ''  %>
  </p>

 <p>
    <%= f.label :phone %><br />
    <%= f.text_field :phone , placeholder: current_order.order_checkouts.any? ? current_order.order_checkouts.last.phone : '' %>
  </p>

 <p>
    <%= f.label :adress %><br />
    <%= f.text_field :adress , placeholder: current_order.order_checkouts.any? ? current_order.order_checkouts.last.adress : ''  %>
  </p>

 <p>
    <%= f.label :city %><br />
    <%= f.text_field :city , placeholder: current_order.order_checkouts.any? ? current_order.order_checkouts.last.city : ''  %>
  </p>

 <p>
    <%= f.label :state %><br />
    <%= f.text_field :state , placeholder: current_order.order_checkouts.any? ? current_order.order_checkouts.last.state : ''  %>
  </p>

 <p>
    <%= f.label :zip %><br />
    <%= f.number_field :zip , placeholder: current_order.order_checkouts.any? ? current_order.order_checkouts.last.zip : ''  %>
  </p>





<h3>Billing adress</h3>
 <p>
    <%= f.label :bill_name %><br />
    <%= f.text_field :bill_name , placeholder: current_order.order_checkouts.any? ? current_order.order_checkouts.last.bill_name : ''  %>
  </p>
 <p>
    <%= f.label :bill_adress %><br />
    <%= f.text_field :bill_adress , placeholder: current_order.order_checkouts.any? ? current_order.order_checkouts.last.bill_adress : ''  %>
  </p>

 <p>
    <%= f.label :bill_city %><br />
    <%= f.text_field :bill_city , placeholder: current_order.order_checkouts.any? ? current_order.order_checkouts.last.bill_city : ''  %>
  </p>

 <p>
    <%= f.label :bill_state %><br />
    <%= f.text_field :bill_state , placeholder: current_order.order_checkouts.any? ? current_order.order_checkouts.last.bill_state : ''  %>
  </p>

 <p>
    <%= f.label :bill_zip %><br />
    <%= f.number_field :bill_zip , placeholder: current_order.order_checkouts.any? ? current_order.order_checkouts.last.bill_zip : ''  %>
  </p>

  <p>
    <%= f.label :card_type %><br />
    <%= f.select :card_type, [["Visa", "visa"], ["MasterCard", "master"], ["Discover", "discover"], ["American Express", "american_express"]] %>
  </p>
  <p>
    <%= f.label :card_number %><br />
    <%= f.text_field :card_number %>
  </p>
  <p>
    <%= f.label :card_verification, "Card Verification Value (CVV)" %><br />
    <%= f.text_field :card_verification %>
  </p>
  <p>
    <%= f.label :card_expires_on %><br />
    <%= f.date_select :card_expires_on, :discard_day => true, :start_year => Date.today.year, :end_year => (Date.today.year+10), :add_month_numbers => true %>
  </p>

<h4>special instuctions if any</h4>
 <p>
    <%= f.label :instructions %><br />
    <%= f.text_area :instructions, rows: 5  %>
  </p>

  <p><%= f.submit "Submit" %></p>
<% end %>
<br>
</div>
<div id="pay-type" class="col-10 vhcenterp see box" style="height:100%;">
      <div class="col-12 vhcenters seebox center">
    <button class="center new-checkout-b" id="instore-checkout-button" style="">in-store checkout</button><br>
        <%= link_to paypal_path, method: :post do %> 
    <button class="center new-checkout-b" style="" >paypal express</button><br>
        <img src="<%request.base_url%>/assets/images/paypal.gif">
        <%end%>
      </div>
</div>

<div class="col-1"></div>





<script src="<%= request.base_url%>/assets/js/order_checkouts/new.js"></script>


<script>


$(document).ready(function(){
    		                      $("#instore-checkout-button").click(function(){
        		                                                                  $("#instore-form").show();
                                                                              $("#pay-type").hide();
                                                                                
                                                                            });
                            });





</script>

app/views/order_checkouts/purchases.html.erb
<%if $admin%>
<style>
table, th, tr, td { border:solid 1px;}
</style>
    <!-- clear zone3 -->
<div class="col-m-12 col-12 seebox removempb" style="" style="border:2px solid red;">
           <!--   left-side space -->
          <div class="col-1 seebox"></div>
  
          <!--   center-div -->
          <div class="col-10 seebox">

             <h2>purchases.html.erb</h2>
                    
             <% OrderCheckout.all.each.with_index do |this, index = 1|%>
                   
             <% if this.purchased_at && !this.paid_shipped_n_done %>
            
             <div id="order_checkout-<%=this.id%>">
               
                          <table style="width:100%;">
                            <tr>
                              <th colspan="3">Order Checkout <%=index%></th>
                            </tr>
                            <tr>
                              <th>key</th>
                             <th>value</th>
                            </tr>
                            <% this.attributes.each do |j|%>
                            <tr>
                              <td><%=j[0]%></td>
                              <td><%=j[1]%></td>
                            </tr>
                            <%end%>
                          </table>
            
                     
                                           
                        <% this.order_checkout_transactions.each do |oct|%>
                          <table style="width:100%;">
                            <tr>
                              <th colspan="3">Order Checkout Transaction</th>
                            </tr>
                            <tr>
                              <th>key</th>
                             <th>value</th>
                            </tr>
                            <% oct.attributes.each do |j|%>
                            <tr>
                              <td><%=j[0]%></td>
                              <td><%=j[1]%></td>
                            </tr>
                            <%end%>
                          </table>
                            <%end%>
            
            
                         <h4>items bought</h4>
                         <%this.checkout_paid_items.each do |item|%>
                                                 
            
                           <table style="width:100%;">
                              <tr>
                                <th colspan="3">Paid Item</th>
                              </tr>
                              <tr>
                                <th>key</th>
                               <th>value</th>
                              </tr>
                             <%item.attributes.each do |itema|%>
                              <tr>
                                <td><%=itema[0]%></td>
                                <td><%=itema[1]%></td>
                              </tr>
                             <%end%>
                            </table>
                                      
            
                                         <%end%>
                                  
                                    <br>
                                    <button><%= link_to "Done", [this], method: :put, remote: true %></button>

                                    <p>===============================================================================</p>
                                 </div>

                   <%end%>
  
                          <!--   loop ends -->
               <%end%>
</div>
  
</div>
  
            <!--   right-side space -->
            <div class="col-1 seebox"></div> 

<%end%>

app/views/order_checkouts/show.html.erb
<h1>OrderCheckouts#show</h1>
<p>Find me in app/views/order_checkouts/show.html.erb</p>

app/views/order_checkouts/success.html.erb
<h1>Thank You For Your Purchase!</h1>
<p>we will sortly ship out your product</p>
<button><%= link_to 'Return to Store', root_path %></button>

app/views/order_checkouts/thank_you.html.erb
<h1>Thank You For Your Purchase!</h1>
<% purchase = OrderCheckout.where(Order_id: session[:order_id]).last.order_checkout_transactions.last%>
<p>We will sortly ship out your product</p>
<p>Your confirmation number is:<%= purchase.params["pal_button"] ? purchase.params["ipn_track_id"] : purchase.authorization%><p>
<p>Please keep your confirmation number for your records.</p>  
<p>Your card will be charged in the ammount of $<%= purchase.params["pal_button"] ? purchase.params["payment_gross"] : purchase.params["amount"]%></p>
<button><%= link_to 'Return to Store', root_path %></button>

app/views/order_checkouts/update.js.erb
<% this = OrderCheckout.find(params[:id])%>

   $('#order_checkout-' +<%= this.id %>).hide();
 