config/routes.rb
Rails.application.routes.draw do

resources :order_checkouts

resources :main_categories do
  resources :main_category_pics
end
  

resources :main_categories do
  resources :items do 
    resources :item_pics
  end 
end

  

  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]  
 

  devise_for :users
   resources :users#, only: [:update]

  
  get 'about' => 'welcome#about'
  
  root to: 'main_categories#index'

get "checkout", to: "items#checkout"

get "purchases", to: "order_checkouts#purchases"
get "thank_you", to: "order_checkouts#thank_you"
get "seeds", to: "order_items#seeds"
post "paypal", to: "order_checkouts#pal_purchase"
post "pal_return", to: "order_checkouts#pal_return"

end

app/models/checkout_paid_item.rb
class CheckoutPaidItem < ActiveRecord::Base
  belongs_to :order_checkout
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :main_category
  has_many :item_pics
  has_many :order_items, dependent: :destroy
  default_scope { where(active: true) }
end

app/models/item_pic.rb
class ItemPic < ActiveRecord::Base
  belongs_to :item, dependent: :destroy
  mount_uploader :pic_url, PicUploader
 # serialize :description
  
  #rescue ActiveMerchant::ActiveMerchantError => e
  #self.description        = {}
  
end
#ItemPic.where(name:"template").last.description['Build']

app/models/main_category.rb
class MainCategory < ActiveRecord::Base
  has_many :main_category_pics, dependent: :destroy

  has_many :items, dependent: :destroy

end

app/models/main_category_pic.rb
class MainCategoryPic < ActiveRecord::Base
  belongs_to :main_category
  mount_uploader :pic_url, PicUploader
    serialize :description
  
  #rescue ActiveMerchant::ActiveMerchantError => e
  #self.description        = {}
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items, dependent: :destroy
  has_many :order_checkouts
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_checkout.rb
class OrderCheckout < ActiveRecord::Base
  belongs_to :order
  has_many :order_checkout_transactions, dependent: :destroy
  has_many :checkout_paid_items, dependent: :destroy
  attr_accessor :card_number, :card_verification
 # validate :validate_card, :on => :create
  
 
  
  def purchase(current_order, params)
    response = GATEWAY.purchase(
                                price_in_cents(current_order),
                                credit_card(params),
                                purchase_options(params)
                              )
    
    
    order_checkout_transactions.create!(:action => "purchase", :amount => price_in_cents(current_order), :response => response)
   # cart.update_attribute(:purchased_at, Time.now)  ## this needs to work but dont have a purchased_at attribute in any model
      if response.success?
    response.success?
      end
  end
  
  def price_in_cents(current_order)
    (current_order.subtotal*100 + 400).round 
  end

  private
  
  def purchase_options(params)
    {
      :ip => ip_address,
      :billing_address => {
        :name     => params[:order_checkout][:bill_name],
        :address1 => params[:order_checkout][:bill_adress],
        :city     => params[:order_checkout][:bill_city],
        :state    => params[:order_checkout][:bill_state],
        :country  => "US",
        :zip      => params[:order_checkout][:bill_zip]
      }
    }
  end
  
#  def validate_card(params)
 #   if !$params[:pal_button]
 #     unless credit_card.valid?
 #       credit_card.errors.full_messages.each do |message|
 #         errors.add_to_base message
#        end
 #     end
  #  end
 # end
  
  def credit_card(params)
        logger.debug puts "
                      debbuger
                      \n #{  }
                    
                      " 
               # exit
     if Rails.env.production?
   
          @credit_card ||= ActiveMerchant::Billing::CreditCard.new(

                first_name: params[:order_checkout][:first_name],
                last_name:params[:order_checkout][:last_name],
                number: params[:order_checkout][:card_number],
                month: params[:order_checkout]["card_expires_on(2i)"],
                year:params[:order_checkout]["card_expires_on(1i)"],
                verification_value: params[:order_checkout][:card_verification]   )
       else
           @credit_card ||= ActiveMerchant::Billing::CreditCard.new(

                first_name: params[:order_checkout][:first_name],
                last_name:params[:order_checkout][:last_name],
                number: params[:order_checkout][:card_number] == '' ? ENV['PAYPAL_CARD_NUMBER'] : params[:order_checkout][:card_number],
                month: params[:order_checkout]["card_expires_on(2i)"],
                year:'2020',
                verification_value: '345'   )
     end
       
  end
  
  
  
  
  
  
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :item_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      item.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def item_present
    if item.nil?
      errors.add(:item, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
          #:validatable, 
          :confirmable
 
  
   def admin?
   role == 'admin'
 end
 
 def moderator?
   role == 'moderator'
 end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/item_pics_helper.rb
module ItemPicsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_cart_text.html.erb
<%= "#{current_order.order_items.count} Items in Cart ( #{number_to_currency(current_order.subtotal)} )" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>E-Store.com</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <% if request.ssl? %>
 
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
     <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% else %> 
  
    <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  
  <% end %>
  
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
<!--   <link rel="stylesheet" href="https://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css"> -->
  <link rel="stylesheet" type="text/css" href="<%= request.base_url%>/assets/css/main_categories/index.css">
   <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
   <script src="assets/js/main_categories/index.js"></script>
   <script src="https://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"></script>
</head>
<body>
    
    
   
<!-- top menu bar -->
 
<div class="col-m-12 col-12 seebox " style=" background-color:#5F5F5F; position:fixed; z-index: 5;" >

  <%= link_to cart_path do%>
    <div class="col-9 col-m-9 col-p-9  seebox buttonbox" id="button" style="background-color:#5F5F5F;">
      <p class='cart-text' style="color:white;"> <%= render 'layouts/cart_text'%></p>
    </div>
  <%end%>
  
   <%= link_to root_path do%>
  <div class="col-1 col-m-3 col-p-3  seebox buttonbox " id="button" style="float:left; background-color:#5F5F5F;" ><p style="color:white;">home</p></div>
   <%end%>

 </div>
  
  <%if current_user%>
  <%= link_to "Sign out",destroy_user_session_path, method: :delete %>
  <%end%>
  
  

  
       <% if $admin %>
  
   <!-- clear zone1 -->
<div class="col-m-12 col-12 seebox" style="height:50px;  ">
</div>   
  
  
                 <ul class="nav nav-tabs">

                       <li><%= link_to "E-Store", root_path %></li>

                       <li><%= link_to "About", about_path %></li>

                       <li><%= link_to "Purchases", purchases_path %></li>

                       <li><%= link_to "Seeds", seeds_path %></li>

                      <div class="pull-right user-info">
                           <% if current_user %>
                              Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
                           <% else %>
                             <%= link_to "Sign In", new_user_session_path %> or 
                             <%= link_to "Sign Up", new_user_registration_path %>
                           <% end %>
                       </div>
                </ul>
     
       
     
       <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>
     
     

    <%end%>  
  
    <!-- clear zone2 -->
<div class="col-m-12 col-12 seebox removempb" style="height:70px;" style="">
</div> 
  

      <%= yield %>
     

<!-- <script src="assets/js/application.js"></script> -->
 
   <script>

 $(document).ready(function(){
                                    $(document).foundation();
                                  })
 

</script>
    
    
</body>
</html>